POST  http://localhost:3000/userinfo
Content-Type: application/json
User-Agent: Zoom-api-Jwt-Request

{
    "email_address": "jsupsupin@codingdojo.com"
}

###
POST http://localhost:3000/meetings
Content-Type: application/json
User-Agent: Zoom-api-Jwt-Request

{
    "email_address": "jsupsupin@codingdojo.com"
}

###
POST http://localhost:3000/create_meeting
Content-Type: application/json
User-Agent: Zoom-api-Jwt-Request

{
    "email_address": "jsupsupin@codingdojo.com",
    "post_data": {
        "topic": "Sample meeting 123",
        "type": 1,
        "timezone": "Asia/Shanghai"
    }
}

###
POST http://localhost:3000/participants
Content-Type: application/json
User-Agent: Zoom-api-Jwt-Request

{
    "meeting_id": "xafmRe8QT2GA4TiCBLpvyw=="
}

###
POST http://localhost:3000/recordings
Content-Type: application/json
User-Agent: Zoom-api-Jwt-Request

{
    "email_address": "jsupsupin@codingdojo.com",
    "params": {
        "from": "2022-01-01",
        "to": "2023-01-01",
        "page_size": 30
    }
}

###
POST http://localhost:3000/registrants
Content-Type: application/json
User-Agent: Zoom-api-Jwt-Request

{
    "recording_id": "EOYTkts8Q1KZLc/nEoZS3A==",
    "params": {
        "page_number": 1,
        "page_size": 33
    }
}

###
POST http://localhost:3000/add_registrant
Content-Type: application/json
User-Agent: Zoom-api-Jwt-Request

{
    "meeting_id": "86558754552",
    "post_data": {
        "first_name": "Jill",
        "last_name": "Chill",
        "email": "replacemewithvalid@email.com",
        "language": "en-US",
        "auto_approve": true
    }
}